// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using challenge_total.Data;

#nullable disable

namespace challenge_total.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231027184824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("challenge_total.Data.Entities.Button", b =>
                {
                    b.Property<int>("ButtonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButtonID"));

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.HasKey("ButtonID");

                    b.ToTable("Buttons");
                });
#pragma warning restore 612, 618
        }
    }
}
